--Important: Before running this script it is assumed the external_key of the journals termlist 'dgfm:journal_references'
--The references CSV file to import must of been generated by the XSLT XML convertor script
--Tags to replace in this script are as follows
--<reference_csv_file_path>
--Path format (on mac) should be like '/users/joebloggs/tblSpeciesTrait.csv'
--If running in PSQL on a server, then the path is from the PSQL working directory, you can find this out by typing "\! pwd" inside PSQL

/*
Data exported from MS Access as text files, suffix .csv, field names in first row, " delimiter.
Open each file in notepad and save as UTF-8
Open each file in Notepad++ and convert to UTF-8 without BOM
*/

-- NOW, import the species

create schema if not exists dgfm;
set search_path TO dgfm, public;

DROP TABLE IF EXISTS tbl_reference_data;

CREATE TABLE tbl_reference_data (
  id serial primary key not null,
  data_type varchar,
  data_value varchar
);

COPY tbl_reference_data
FROM '<reference_csv_file_path>'
WITH DELIMITER ','
ENCODING 'UTF-8'
CSV HEADER;