--- Sample Attributes must be loaded first.

--- MNHNL Location types.
INSERT INTO termlists (title, description, created_on, created_by_id, updated_on, updated_by_id, external_key)
VALUES ('LocationTypes', 'MNHNL Location types', now(), 1, now(), 1, 'mnhnl:loctype');
SELECT insert_term('Lux5KSquare', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('ReptileLocation', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('WinterBats Confirmed', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('WinterBats Submitted', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Butterflies2', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Summer Bats Submitted', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Summer Bats Confirmed', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Lux1KSquare', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Dormice', 'eng', null, 'mnhnl:loctype');
SELECT insert_term('Amphibians', 'eng', null, 'mnhnl:loctype');

-- after the following are set up, need to set their structure blocks (sample attributes), as well as their website allocation

CREATE OR REPLACE FUNCTION tmp_add_term(t character varying(100), lang_iso character(3), list integer, list_external_key character varying) RETURNS integer AS
$BODY$
DECLARE
  m_id integer;
  t_id integer;
  l_id integer;
BEGIN
    l_id := CASE WHEN list IS NULL THEN (SELECT id FROM termlists WHERE external_key=list_external_key) ELSE list END;

    t_id := nextval('terms_id_seq'::regclass);

    INSERT INTO terms (id, term, language_id, created_on, created_by_id, updated_on, updated_by_id)
    VALUES (t_id, t, (SELECT id from languages WHERE iso = lang_iso), now(), 1, now(), 1);

    m_id := currval('meanings_id_seq'::regclass);

    INSERT INTO termlists_terms (term_id, termlist_id, meaning_id, preferred, created_on, created_by_id, updated_on, updated_by_id)
    VALUES (t_id, l_id, m_id, 'f', now(), 1, now(), 1);

    RETURN 1;
END
$BODY$
LANGUAGE 'plpgsql';

--- There are no new Location Attributes used for COBIMO: Common Bird Monitoring: mnhnl_bird_transect_walks
--- There are no new Location Attributes used for Butterflies1: Butterfly Monitoring: mnhnl_butterflies

--- The following new Location Attributes are used for Winter Bats: mnhnl_bats

INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Village', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Commune', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO termlists (title, description, created_on, created_by_id, updated_on, updated_by_id, external_key)
VALUES ('BatSiteType', 'Site Type', now(), 1, now(), 1, 'bats:sitetype');
SELECT insert_term('Hollow tree', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Arbre creux', 'fra', null, 'bats:sitetype');
SELECT insert_term('Slate quarry', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Ardoisière', 'fra', null, 'bats:sitetype');
SELECT insert_term('Bunker', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Bunker', 'fra', null, 'bats:sitetype');
SELECT insert_term('Underground quarry', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Carrière souterraine', 'fra', null, 'bats:sitetype');
SELECT insert_term('Military pillbox', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Casemate', 'fra', null, 'bats:sitetype');
SELECT insert_term('Cellar', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Cave', 'fra', null, 'bats:sitetype');
SELECT insert_term('Bell tower or steeple', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Clocher', 'fra', null, 'bats:sitetype');
SELECT insert_term('Loft', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Comble', 'fra', null, 'bats:sitetype');
SELECT insert_term('Fort', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Fort', 'fra', null, 'bats:sitetype');
SELECT insert_term('Icehouse', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Glacière', 'fra', null, 'bats:sitetype');
SELECT insert_term('Granery', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Grenier', 'fra', null, 'bats:sitetype');
SELECT insert_term('Natural cave or fault', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Grotte ou faille naturelle', 'fra', null, 'bats:sitetype');
SELECT insert_term('Semi-natural cave or fault', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Grotte ou faille semi-naturelle', 'fra', null, 'bats:sitetype');
SELECT insert_term('Mine', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Mine', 'fra', null, 'bats:sitetype');
SELECT insert_term('Nestbox', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Nichoir', 'fra', null, 'bats:sitetype');
SELECT insert_term('Artificial underground', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Souterrain artificiel', 'fra', null, 'bats:sitetype');
SELECT insert_term('Tunnel', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Tunnel', 'fra', null, 'bats:sitetype');
SELECT insert_term('Shutter', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Volet', 'fra', null, 'bats:sitetype');
SELECT insert_term('Other', 'eng', null, 'bats:sitetype');
SELECT tmp_add_term('Autre', 'fra', null, 'bats:sitetype');
UPDATE termlists_terms SET sort_order = 10*id WHERE termlist_id = (SELECT id FROM termlists WHERE external_key='bats:sitetype');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, termlist_id, multi_value, public) VALUES (
	'Site type', 'L', now(), 1, now(), 1, (select id from termlists where external_key='bats:sitetype'), 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Site type other', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Precision', 'I', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Code GSL', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Depth', 'I', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (	caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Development', 'I', now(), 1, now(), 1, 'f', 't');

--- There are no new Location Attributes used for Butterflies2: Butterfly de Jours: mnhnl_butterflies2
--- But it does use a termlist for the location names.

INSERT INTO termlists (title, description, created_on, created_by_id, updated_on, updated_by_id, external_key)
VALUES ('MNHNL Butterfly de Jour Sites', 'Site Names', now(), 1, now(), 1, 'butterfly2:Sites');
SELECT insert_term('1', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('2', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('3', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('4', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('5', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('6', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('7', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('8', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('9', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('10', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('11', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('12', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('13', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('14', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('15', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('16', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('17', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('18', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('19', 'eng', null, 'butterfly2:Sites'); 
SELECT insert_term('20', 'eng', null, 'butterfly2:Sites'); 
UPDATE termlists_terms SET sort_order = 10*id WHERE termlist_id = (SELECT id FROM termlists WHERE external_key='butterfly2:Sites');

--- The following new Location Attributes are used for Reptiles: mnhnl_reptiles

INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Creator', 'T', now(), 1, now(), 1, 'f', 't');

--- The following new Location Attributes are used for Summer Bats: mnhnl_bats2
--- Commune, village and Precision are used from the Bats form.
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Address number', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Street', 'T', now(), 1, now(), 1, 'f', 't');
--- Commune is used from Winter Bats
INSERT INTO termlists (title, description, created_on, created_by_id, updated_on, updated_by_id, external_key)
VALUES ('Bat2SiteType', 'Site Type 2', now(), 1, now(), 1, 'bats2:sitetype');
SELECT insert_term('Hollow tree', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Bunker', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Cellar', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Bell tower or steeple', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Loft', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Fort', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Granery', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Nestbox', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Tunnel', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Shutter', 'eng', null, 'bats2:sitetype');
SELECT insert_term('Other', 'eng', null, 'bats2:sitetype');
UPDATE termlists_terms SET sort_order = 10*id WHERE termlist_id = (SELECT id FROM termlists WHERE external_key='bats2:sitetype');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, termlist_id, multi_value, public) VALUES (
	'Site type2', 'L', now(), 1, now(), 1, (select id from termlists where external_key='bats2:sitetype'), 't', 't');
--- Site type other from Bats1

--- The following new Location Attributes are used for Amphibian Sites: uses the same form as reptiles
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Place', 'T', now(), 1, now(), 1, 'f', 't');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, multi_value, public) VALUES (
	'Square', 'T', now(), 1, now(), 1, 'f', 't');

-- The village in Bats 2 is to be converted to a autocomplete termlist

INSERT INTO termlists (title, description, created_on, created_by_id, updated_on, updated_by_id, external_key)
VALUES ('Village', 'Luxembourg Villages and Localities', now(), 1, now(), 1, 'lux:village');
SELECT insert_term('Abweiler', 'eng', null, 'lux:village');
SELECT insert_term('Aechelbur', 'eng', null, 'lux:village');
SELECT insert_term('Aéroport de Luxembourg', 'eng', null, 'lux:village');
SELECT insert_term('Ahn', 'eng', null, 'lux:village');
SELECT insert_term('Akescht', 'eng', null, 'lux:village');
SELECT insert_term('Alef', 'eng', null, 'lux:village');
SELECT insert_term('Allerborn', 'eng', null, 'lux:village');
SELECT insert_term('Alscheid', 'eng', null, 'lux:village');
SELECT insert_term('Altlinster', 'eng', null, 'lux:village');
SELECT insert_term('Altrier', 'eng', null, 'lux:village');
SELECT insert_term('Altwies', 'eng', null, 'lux:village');
SELECT insert_term('Alzingen', 'eng', null, 'lux:village');
SELECT insert_term('Angelsberg', 'eng', null, 'lux:village');
SELECT insert_term('Ansembourg', 'eng', null, 'lux:village');
SELECT insert_term('Arsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Aspelt', 'eng', null, 'lux:village');
SELECT insert_term('Assel', 'eng', null, 'lux:village');
SELECT insert_term('Asselborn', 'eng', null, 'lux:village');
SELECT insert_term('Asselscheier', 'eng', null, 'lux:village');
SELECT insert_term('Bamerdall', 'eng', null, 'lux:village');
SELECT insert_term('Bannheck', 'eng', null, 'lux:village');
SELECT insert_term('Banzelt', 'eng', null, 'lux:village');
SELECT insert_term('Basbellain', 'eng', null, 'lux:village');
SELECT insert_term('Bascharage', 'eng', null, 'lux:village');
SELECT insert_term('Baschleiden', 'eng', null, 'lux:village');
SELECT insert_term('Bastendorf', 'eng', null, 'lux:village');
SELECT insert_term('Bavigne', 'eng', null, 'lux:village');
SELECT insert_term('Beaufort', 'eng', null, 'lux:village');
SELECT insert_term('Bech', 'eng', null, 'lux:village');
SELECT insert_term('Bech-Kleinmacher', 'eng', null, 'lux:village');
SELECT insert_term('Beckerich', 'eng', null, 'lux:village');
SELECT insert_term('Beggen', 'eng', null, 'lux:village');
SELECT insert_term('Beidweiler', 'eng', null, 'lux:village');
SELECT insert_term('Beiler', 'eng', null, 'lux:village');
SELECT insert_term('Beiler Käsfurt', 'eng', null, 'lux:village');
SELECT insert_term('Belair', 'eng', null, 'lux:village');
SELECT insert_term('Belvaux', 'eng', null, 'lux:village');
SELECT insert_term('Berbourg', 'eng', null, 'lux:village');
SELECT insert_term('Berchem', 'eng', null, 'lux:village');
SELECT insert_term('Berdorf', 'eng', null, 'lux:village');
SELECT insert_term('Béreldange', 'eng', null, 'lux:village');
SELECT insert_term('Berg', 'eng', null, 'lux:village');
SELECT insert_term('Bergem', 'eng', null, 'lux:village');
SELECT insert_term('Beringen', 'eng', null, 'lux:village');
SELECT insert_term('Beringerberg', 'eng', null, 'lux:village');
SELECT insert_term('Berlé', 'eng', null, 'lux:village');
SELECT insert_term('Berschbach', 'eng', null, 'lux:village');
SELECT insert_term('Bertrange', 'eng', null, 'lux:village');
SELECT insert_term('Bettange-sur-Mess', 'eng', null, 'lux:village');
SELECT insert_term('Bettborn', 'eng', null, 'lux:village');
SELECT insert_term('Bettel', 'eng', null, 'lux:village');
SELECT insert_term('Bettembourg', 'eng', null, 'lux:village');
SELECT insert_term('Bettendorf', 'eng', null, 'lux:village');
SELECT insert_term('Betzdorf', 'eng', null, 'lux:village');
SELECT insert_term('Beyren', 'eng', null, 'lux:village');
SELECT insert_term('Bierg', 'eng', null, 'lux:village');
SELECT insert_term('Biergerkräiz', 'eng', null, 'lux:village');
SELECT insert_term('Bigelbaach', 'eng', null, 'lux:village');
SELECT insert_term('Bigonville', 'eng', null, 'lux:village');
SELECT insert_term('Biissermillen', 'eng', null, 'lux:village');
SELECT insert_term('Bill', 'eng', null, 'lux:village');
SELECT insert_term('Bilsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Binsfeld', 'eng', null, 'lux:village');
SELECT insert_term('Bissen', 'eng', null, 'lux:village');
SELECT insert_term('Bivange', 'eng', null, 'lux:village');
SELECT insert_term('Bivels', 'eng', null, 'lux:village');
SELECT insert_term('Biwer', 'eng', null, 'lux:village');
SELECT insert_term('Biwisch', 'eng', null, 'lux:village');
SELECT insert_term('Blaschette', 'eng', null, 'lux:village');
SELECT insert_term('Blummendall', 'eng', null, 'lux:village');
SELECT insert_term('Bockholtz', 'eng', null, 'lux:village');
SELECT insert_term('Boevange', 'eng', null, 'lux:village');
SELECT insert_term('Boevange-sur-Attert', 'eng', null, 'lux:village');
SELECT insert_term('Bofferdange', 'eng', null, 'lux:village');
SELECT insert_term('Bollendorf-Pont', 'eng', null, 'lux:village');
SELECT insert_term('Bomicht', 'eng', null, 'lux:village');
SELECT insert_term('Bonnal', 'eng', null, 'lux:village');
SELECT insert_term('Bonnevoie', 'eng', null, 'lux:village');
SELECT insert_term('Born', 'eng', null, 'lux:village');
SELECT insert_term('Boudler', 'eng', null, 'lux:village');
SELECT insert_term('Boudlerbaach', 'eng', null, 'lux:village');
SELECT insert_term('Boulaide', 'eng', null, 'lux:village');
SELECT insert_term('Bour', 'eng', null, 'lux:village');
SELECT insert_term('Bourglinster', 'eng', null, 'lux:village');
SELECT insert_term('Bourscheid', 'eng', null, 'lux:village');
SELECT insert_term('Boursdorf', 'eng', null, 'lux:village');
SELECT insert_term('Bous', 'eng', null, 'lux:village');
SELECT insert_term('Boxhorn', 'eng', null, 'lux:village');
SELECT insert_term('Brachtenbach', 'eng', null, 'lux:village');
SELECT insert_term('Brameschhaff', 'eng', null, 'lux:village');
SELECT insert_term('Brandenbourg', 'eng', null, 'lux:village');
SELECT insert_term('Brattert', 'eng', null, 'lux:village');
SELECT insert_term('Breidfeld', 'eng', null, 'lux:village');
SELECT insert_term('Breidweiler', 'eng', null, 'lux:village');
SELECT insert_term('Breinert', 'eng', null, 'lux:village');
SELECT insert_term('Bricherhaff', 'eng', null, 'lux:village');
SELECT insert_term('Bridel', 'eng', null, 'lux:village');
SELECT insert_term('Broderbour', 'eng', null, 'lux:village');
SELECT insert_term('Brouch', 'eng', null, 'lux:village');
SELECT insert_term('Budersberg', 'eng', null, 'lux:village');
SELECT insert_term('Büderscheid', 'eng', null, 'lux:village');
SELECT insert_term('Bürden', 'eng', null, 'lux:village');
SELECT insert_term('Burange', 'eng', null, 'lux:village');
SELECT insert_term('Burmerange', 'eng', null, 'lux:village');
SELECT insert_term('Burschtermillen', 'eng', null, 'lux:village');
SELECT insert_term('Buschdorf', 'eng', null, 'lux:village');
SELECT insert_term('Buschrodt', 'eng', null, 'lux:village');
SELECT insert_term('Butzebierg', 'eng', null, 'lux:village');
SELECT insert_term('Calmus', 'eng', null, 'lux:village');
SELECT insert_term('Canach', 'eng', null, 'lux:village');
SELECT insert_term('Cap', 'eng', null, 'lux:village');
SELECT insert_term('Capellen', 'eng', null, 'lux:village');
SELECT insert_term('Cents', 'eng', null, 'lux:village');
SELECT insert_term('Cessange', 'eng', null, 'lux:village');
SELECT insert_term('Christnach', 'eng', null, 'lux:village');
SELECT insert_term('Cinqfontaines', 'eng', null, 'lux:village');
SELECT insert_term('Clausen', 'eng', null, 'lux:village');
SELECT insert_term('Clemency', 'eng', null, 'lux:village');
SELECT insert_term('Clervaux', 'eng', null, 'lux:village');
SELECT insert_term('Closbierg', 'eng', null, 'lux:village');
SELECT insert_term('Colbette', 'eng', null, 'lux:village');
SELECT insert_term('Colmar', 'eng', null, 'lux:village');
SELECT insert_term('Colmar-Berg', 'eng', null, 'lux:village');
SELECT insert_term('Colpach-Bas', 'eng', null, 'lux:village');
SELECT insert_term('Colpach-Haut', 'eng', null, 'lux:village');
SELECT insert_term('Consdorf', 'eng', null, 'lux:village');
SELECT insert_term('Consthum', 'eng', null, 'lux:village');
SELECT insert_term('Contern', 'eng', null, 'lux:village');
SELECT insert_term('Crauthem', 'eng', null, 'lux:village');
SELECT insert_term('Crendal', 'eng', null, 'lux:village');
SELECT insert_term('Cruchten', 'eng', null, 'lux:village');
SELECT insert_term('Dahl', 'eng', null, 'lux:village');
SELECT insert_term('Dahlem', 'eng', null, 'lux:village');
SELECT insert_term('Dalheim', 'eng', null, 'lux:village');
SELECT insert_term('Dasbourg-Pont', 'eng', null, 'lux:village');
SELECT insert_term('Deiffelt', 'eng', null, 'lux:village');
SELECT insert_term('Dellen', 'eng', null, 'lux:village');
SELECT insert_term('Dellt', 'eng', null, 'lux:village');
SELECT insert_term('Derenbach', 'eng', null, 'lux:village');
SELECT insert_term('Dickeschbur', 'eng', null, 'lux:village');
SELECT insert_term('Dickt', 'eng', null, 'lux:village');
SELECT insert_term('Dickweiler', 'eng', null, 'lux:village');
SELECT insert_term('Diekirch', 'eng', null, 'lux:village');
SELECT insert_term('Differdange', 'eng', null, 'lux:village');
SELECT insert_term('Dillingen', 'eng', null, 'lux:village');
SELECT insert_term('Dippach', 'eng', null, 'lux:village');
SELECT insert_term('Dippach-Gare', 'eng', null, 'lux:village');
SELECT insert_term('Dirbech', 'eng', null, 'lux:village');
SELECT insert_term('Doennange', 'eng', null, 'lux:village');
SELECT insert_term('Domaine d''Olm', 'eng', null, 'lux:village');
SELECT insert_term('Dommeldange', 'eng', null, 'lux:village');
SELECT insert_term('Doncols', 'eng', null, 'lux:village');
SELECT insert_term('Dondelange', 'eng', null, 'lux:village');
SELECT insert_term('Dorscheid', 'eng', null, 'lux:village');
SELECT insert_term('Dosterthaff', 'eng', null, 'lux:village');
SELECT insert_term('Drauffelt', 'eng', null, 'lux:village');
SELECT insert_term('Dreiborn', 'eng', null, 'lux:village');
SELECT insert_term('Drinklange', 'eng', null, 'lux:village');
SELECT insert_term('Dudelange', 'eng', null, 'lux:village');
SELECT insert_term('Echternach', 'eng', null, 'lux:village');
SELECT insert_term('Ehlange', 'eng', null, 'lux:village');
SELECT insert_term('Ehlerange', 'eng', null, 'lux:village');
SELECT insert_term('Ehnen', 'eng', null, 'lux:village');
SELECT insert_term('Ehner', 'eng', null, 'lux:village');
SELECT insert_term('Eich', 'eng', null, 'lux:village');
SELECT insert_term('Eischen', 'eng', null, 'lux:village');
SELECT insert_term('Eisenborn', 'eng', null, 'lux:village');
SELECT insert_term('Ell', 'eng', null, 'lux:village');
SELECT insert_term('Ellange', 'eng', null, 'lux:village');
SELECT insert_term('Ellange-Gare', 'eng', null, 'lux:village');
SELECT insert_term('Eltz', 'eng', null, 'lux:village');
SELECT insert_term('Elvange', 'eng', null, 'lux:village');
SELECT insert_term('Emerange', 'eng', null, 'lux:village');
SELECT insert_term('Emeschbaach', 'eng', null, 'lux:village');
SELECT insert_term('Enscherange', 'eng', null, 'lux:village');
SELECT insert_term('Eppeldorf', 'eng', null, 'lux:village');
SELECT insert_term('Ermsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Ernster', 'eng', null, 'lux:village');
SELECT insert_term('Ernzen', 'eng', null, 'lux:village');
SELECT insert_term('Erpeldange', 'eng', null, 'lux:village');
SELECT insert_term('Ersange', 'eng', null, 'lux:village');
SELECT insert_term('Esch-Belval', 'eng', null, 'lux:village');
SELECT insert_term('Eschdorf', 'eng', null, 'lux:village');
SELECT insert_term('Eschette', 'eng', null, 'lux:village');
SELECT insert_term('Esch-sur-Alzette', 'eng', null, 'lux:village');
SELECT insert_term('Esch-sur-Sûre', 'eng', null, 'lux:village');
SELECT insert_term('Eschweiler', 'eng', null, 'lux:village');
SELECT insert_term('Eselborn', 'eng', null, 'lux:village');
SELECT insert_term('Essingen', 'eng', null, 'lux:village');
SELECT insert_term('Ettelbruck', 'eng', null, 'lux:village');
SELECT insert_term('Everlange', 'eng', null, 'lux:village');
SELECT insert_term('Faubourg', 'eng', null, 'lux:village');
SELECT insert_term('Fausermillen', 'eng', null, 'lux:village');
SELECT insert_term('Féischterbierg', 'eng', null, 'lux:village');
SELECT insert_term('Fennange', 'eng', null, 'lux:village');
SELECT insert_term('Fënsterdall', 'eng', null, 'lux:village');
SELECT insert_term('Fentange', 'eng', null, 'lux:village');
SELECT insert_term('Fetschenhaff', 'eng', null, 'lux:village');
SELECT insert_term('Feulen', 'eng', null, 'lux:village');
SELECT insert_term('Filsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Findel', 'eng', null, 'lux:village');
SELECT insert_term('Fingig', 'eng', null, 'lux:village');
SELECT insert_term('Fischbach', 'eng', null, 'lux:village');
SELECT insert_term('Flatzbur', 'eng', null, 'lux:village');
SELECT insert_term('Flaxweiler', 'eng', null, 'lux:village');
SELECT insert_term('Fléiber', 'eng', null, 'lux:village');
SELECT insert_term('Fléibur', 'eng', null, 'lux:village');
SELECT insert_term('Foetz', 'eng', null, 'lux:village');
SELECT insert_term('Folkendange', 'eng', null, 'lux:village');
SELECT insert_term('Folschette', 'eng', null, 'lux:village');
SELECT insert_term('Fouhren', 'eng', null, 'lux:village');
SELECT insert_term('Freckeisen', 'eng', null, 'lux:village');
SELECT insert_term('Fridbësch', 'eng', null, 'lux:village');
SELECT insert_term('Frisange', 'eng', null, 'lux:village');
SELECT insert_term('Fuussekaul', 'eng', null, 'lux:village');
SELECT insert_term('Gaichel', 'eng', null, 'lux:village');
SELECT insert_term('Gare', 'eng', null, 'lux:village');
SELECT insert_term('Gare de Sandweiler-Contern', 'eng', null, 'lux:village');
SELECT insert_term('Garnich', 'eng', null, 'lux:village');
SELECT insert_term('Gasperich', 'eng', null, 'lux:village');
SELECT insert_term('Géidgermillen', 'eng', null, 'lux:village');
SELECT insert_term('Geyershaff', 'eng', null, 'lux:village');
SELECT insert_term('Gilsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Girst', 'eng', null, 'lux:village');
SELECT insert_term('Girsterklaus', 'eng', null, 'lux:village');
SELECT insert_term('Givenich', 'eng', null, 'lux:village');
SELECT insert_term('Glabach', 'eng', null, 'lux:village');
SELECT insert_term('Godbrange', 'eng', null, 'lux:village');
SELECT insert_term('Goebelsmühle', 'eng', null, 'lux:village');
SELECT insert_term('Goeblange', 'eng', null, 'lux:village');
SELECT insert_term('Goedange', 'eng', null, 'lux:village');
SELECT insert_term('Goesdorf', 'eng', null, 'lux:village');
SELECT insert_term('Goetzingen', 'eng', null, 'lux:village');
SELECT insert_term('Gondel', 'eng', null, 'lux:village');
SELECT insert_term('Gonderange', 'eng', null, 'lux:village');
SELECT insert_term('Gosseldange', 'eng', null, 'lux:village');
SELECT insert_term('Gostingen', 'eng', null, 'lux:village');
SELECT insert_term('Gralingen', 'eng', null, 'lux:village');
SELECT insert_term('Grasbësch', 'eng', null, 'lux:village');
SELECT insert_term('Grass', 'eng', null, 'lux:village');
SELECT insert_term('Graulinster', 'eng', null, 'lux:village');
SELECT insert_term('Greisch', 'eng', null, 'lux:village');
SELECT insert_term('Greiveldange', 'eng', null, 'lux:village');
SELECT insert_term('Gréiweknapp', 'eng', null, 'lux:village');
SELECT insert_term('Grevels', 'eng', null, 'lux:village');
SELECT insert_term('Grevenmacher', 'eng', null, 'lux:village');
SELECT insert_term('Grindhausen', 'eng', null, 'lux:village');
SELECT insert_term('Groësteen', 'eng', null, 'lux:village');
SELECT insert_term('Grondhaff', 'eng', null, 'lux:village');
SELECT insert_term('Gronn', 'eng', null, 'lux:village');
SELECT insert_term('Grosbous', 'eng', null, 'lux:village');
SELECT insert_term('Grümmelscheid', 'eng', null, 'lux:village');
SELECT insert_term('Haard', 'eng', null, 'lux:village');
SELECT insert_term('Haarderbaach', 'eng', null, 'lux:village');
SELECT insert_term('Hachiville', 'eng', null, 'lux:village');
SELECT insert_term('Hagen', 'eng', null, 'lux:village');
SELECT insert_term('Haller', 'eng', null, 'lux:village');
SELECT insert_term('Halsbaach', 'eng', null, 'lux:village');
SELECT insert_term('Hamiville', 'eng', null, 'lux:village');
SELECT insert_term('Hamm', 'eng', null, 'lux:village');
SELECT insert_term('Härebierg', 'eng', null, 'lux:village');
SELECT insert_term('Harlange', 'eng', null, 'lux:village');
SELECT insert_term('Hassel', 'eng', null, 'lux:village');
SELECT insert_term('Hautbellain', 'eng', null, 'lux:village');
SELECT insert_term('Hautcharage', 'eng', null, 'lux:village');
SELECT insert_term('Heffingen', 'eng', null, 'lux:village');
SELECT insert_term('Heiderscheid', 'eng', null, 'lux:village');
SELECT insert_term('Heinerscheid', 'eng', null, 'lux:village');
SELECT insert_term('Heischtergronn', 'eng', null, 'lux:village');
SELECT insert_term('Heisdorf', 'eng', null, 'lux:village');
SELECT insert_term('Heispelt', 'eng', null, 'lux:village');
SELECT insert_term('Helfent', 'eng', null, 'lux:village');
SELECT insert_term('Hellange', 'eng', null, 'lux:village');
SELECT insert_term('Helmdange', 'eng', null, 'lux:village');
SELECT insert_term('Helmsange', 'eng', null, 'lux:village');
SELECT insert_term('Hemstal', 'eng', null, 'lux:village');
SELECT insert_term('Herborn', 'eng', null, 'lux:village');
SELECT insert_term('Hermeswiss', 'eng', null, 'lux:village');
SELECT insert_term('Hersberg', 'eng', null, 'lux:village');
SELECT insert_term('Hesperange', 'eng', null, 'lux:village');
SELECT insert_term('Hëttermillen', 'eng', null, 'lux:village');
SELECT insert_term('Hierbermillen', 'eng', null, 'lux:village');
SELECT insert_term('Hierheck', 'eng', null, 'lux:village');
SELECT insert_term('Hinkel', 'eng', null, 'lux:village');
SELECT insert_term('Hivange', 'eng', null, 'lux:village');
SELECT insert_term('Hobscheid', 'eng', null, 'lux:village');
SELECT insert_term('Hoesdorf', 'eng', null, 'lux:village');
SELECT insert_term('Hoffelt', 'eng', null, 'lux:village');
SELECT insert_term('Hollenfels', 'eng', null, 'lux:village');
SELECT insert_term('Holler', 'eng', null, 'lux:village');
SELECT insert_term('Hollerich', 'eng', null, 'lux:village');
SELECT insert_term('Holtz', 'eng', null, 'lux:village');
SELECT insert_term('Holzem', 'eng', null, 'lux:village');
SELECT insert_term('Holzthum', 'eng', null, 'lux:village');
SELECT insert_term('Horas', 'eng', null, 'lux:village');
SELECT insert_term('Hoscheid', 'eng', null, 'lux:village');
SELECT insert_term('Hoscheid-Dickt', 'eng', null, 'lux:village');
SELECT insert_term('Hosingen', 'eng', null, 'lux:village');
SELECT insert_term('Hossebierg', 'eng', null, 'lux:village');
SELECT insert_term('Hostert', 'eng', null, 'lux:village');
SELECT insert_term('Hovelange', 'eng', null, 'lux:village');
SELECT insert_term('Howald', 'eng', null, 'lux:village');
SELECT insert_term('Hünsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Huldange', 'eng', null, 'lux:village');
SELECT insert_term('Huncherange', 'eng', null, 'lux:village');
SELECT insert_term('Hupperdange', 'eng', null, 'lux:village');
SELECT insert_term('Huttange', 'eng', null, 'lux:village');
SELECT insert_term('Imbringen', 'eng', null, 'lux:village');
SELECT insert_term('Ingeldorf', 'eng', null, 'lux:village');
SELECT insert_term('Insenborn', 'eng', null, 'lux:village');
SELECT insert_term('Itzig', 'eng', null, 'lux:village');
SELECT insert_term('Juckefeld', 'eng', null, 'lux:village');
SELECT insert_term('Junglinster', 'eng', null, 'lux:village');
SELECT insert_term('Käerjeng', 'eng', null, 'lux:village');
SELECT insert_term('Kahler', 'eng', null, 'lux:village');
SELECT insert_term('Kalborn', 'eng', null, 'lux:village');
SELECT insert_term('Kalchesbréck', 'eng', null, 'lux:village');
SELECT insert_term('Kalkesbaach', 'eng', null, 'lux:village');
SELECT insert_term('Kalscheier', 'eng', null, 'lux:village');
SELECT insert_term('Kapenaker', 'eng', null, 'lux:village');
SELECT insert_term('Kapweiler', 'eng', null, 'lux:village');
SELECT insert_term('Kaundorf', 'eng', null, 'lux:village');
SELECT insert_term('Kautenbach', 'eng', null, 'lux:village');
SELECT insert_term('Kayl', 'eng', null, 'lux:village');
SELECT insert_term('Kehlen', 'eng', null, 'lux:village');
SELECT insert_term('Kehmen', 'eng', null, 'lux:village');
SELECT insert_term('Keispelt', 'eng', null, 'lux:village');
SELECT insert_term('Keiwelbaach', 'eng', null, 'lux:village');
SELECT insert_term('Kengert', 'eng', null, 'lux:village');
SELECT insert_term('Kiemerchen', 'eng', null, 'lux:village');
SELECT insert_term('Kiischpelt', 'eng', null, 'lux:village');
SELECT insert_term('Kimm', 'eng', null, 'lux:village');
SELECT insert_term('Kirchberg-Centre Européen', 'eng', null, 'lux:village');
SELECT insert_term('Kirchberg-Kiem', 'eng', null, 'lux:village');
SELECT insert_term('Kirchberg-Plateau', 'eng', null, 'lux:village');
SELECT insert_term('Kirchberg-Quartier', 'eng', null, 'lux:village');
SELECT insert_term('Kléck', 'eng', null, 'lux:village');
SELECT insert_term('Kleinbettingen', 'eng', null, 'lux:village');
SELECT insert_term('Kleinhoscheid', 'eng', null, 'lux:village');
SELECT insert_term('Knaphoscheid', 'eng', null, 'lux:village');
SELECT insert_term('Knapp', 'eng', null, 'lux:village');
SELECT insert_term('Kobebour', 'eng', null, 'lux:village');
SELECT insert_term('Kockelscheier', 'eng', null, 'lux:village');
SELECT insert_term('Koedange', 'eng', null, 'lux:village');
SELECT insert_term('Koerich', 'eng', null, 'lux:village');
SELECT insert_term('Koetschette', 'eng', null, 'lux:village');
SELECT insert_term('Köppenhaff', 'eng', null, 'lux:village');
SELECT insert_term('Kopstal', 'eng', null, 'lux:village');
SELECT insert_term('Kräizerbuch', 'eng', null, 'lux:village');
SELECT insert_term('Kréintgeshaff', 'eng', null, 'lux:village');
SELECT insert_term('Kuborn', 'eng', null, 'lux:village');
SELECT insert_term('Lac-de-la-Haute-Sûre', 'eng', null, 'lux:village');
SELECT insert_term('Lafewier', 'eng', null, 'lux:village');
SELECT insert_term('Lallange', 'eng', null, 'lux:village');
SELECT insert_term('Lamadelaine', 'eng', null, 'lux:village');
SELECT insert_term('Lameschmillen', 'eng', null, 'lux:village');
SELECT insert_term('Landscheid', 'eng', null, 'lux:village');
SELECT insert_term('Lannen', 'eng', null, 'lux:village');
SELECT insert_term('Lannenerbierg', 'eng', null, 'lux:village');
SELECT insert_term('Larochette', 'eng', null, 'lux:village');
SELECT insert_term('Lasauvage', 'eng', null, 'lux:village');
SELECT insert_term('Lauterbur', 'eng', null, 'lux:village');
SELECT insert_term('Leekoll', 'eng', null, 'lux:village');
SELECT insert_term('Lehrhaff', 'eng', null, 'lux:village');
SELECT insert_term('Leithum', 'eng', null, 'lux:village');
SELECT insert_term('Lellerhaff', 'eng', null, 'lux:village');
SELECT insert_term('Lellig', 'eng', null, 'lux:village');
SELECT insert_term('Lellingen', 'eng', null, 'lux:village');
SELECT insert_term('Lenningen', 'eng', null, 'lux:village');
SELECT insert_term('Lentzweiler', 'eng', null, 'lux:village');
SELECT insert_term('Leudelange', 'eng', null, 'lux:village');
SELECT insert_term('Leudelange-Gare', 'eng', null, 'lux:village');
SELECT insert_term('Lévelange', 'eng', null, 'lux:village');
SELECT insert_term('Liefrange', 'eng', null, 'lux:village');
SELECT insert_term('Lieler', 'eng', null, 'lux:village');
SELECT insert_term('Limpach', 'eng', null, 'lux:village');
SELECT insert_term('Limpertsberg', 'eng', null, 'lux:village');
SELECT insert_term('Linger', 'eng', null, 'lux:village');
SELECT insert_term('Lintgen', 'eng', null, 'lux:village');
SELECT insert_term('Lipperscheid', 'eng', null, 'lux:village');
SELECT insert_term('Livange', 'eng', null, 'lux:village');
SELECT insert_term('Longsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Lorentzweiler', 'eng', null, 'lux:village');
SELECT insert_term('Lullange', 'eng', null, 'lux:village');
SELECT insert_term('Lultzhausen', 'eng', null, 'lux:village');
SELECT insert_term('Luxembourg', 'eng', null, 'lux:village');
SELECT insert_term('Luxembourg-Gare', 'eng', null, 'lux:village');
SELECT insert_term('Maarkebaach', 'eng', null, 'lux:village');
SELECT insert_term('Machtum', 'eng', null, 'lux:village');
SELECT insert_term('Mamer', 'eng', null, 'lux:village');
SELECT insert_term('Manertchen', 'eng', null, 'lux:village');
SELECT insert_term('Manternach', 'eng', null, 'lux:village');
SELECT insert_term('Mariendall', 'eng', null, 'lux:village');
SELECT insert_term('Marnach', 'eng', null, 'lux:village');
SELECT insert_term('Marscherwald', 'eng', null, 'lux:village');
SELECT insert_term('Marxbierg', 'eng', null, 'lux:village');
SELECT insert_term('Masseler', 'eng', null, 'lux:village');
SELECT insert_term('Maulusmillen', 'eng', null, 'lux:village');
SELECT insert_term('Mecher', 'eng', null, 'lux:village');
SELECT insert_term('Medernach', 'eng', null, 'lux:village');
SELECT insert_term('Medingen', 'eng', null, 'lux:village');
SELECT insert_term('Meispelt', 'eng', null, 'lux:village');
SELECT insert_term('Mensdorf', 'eng', null, 'lux:village');
SELECT insert_term('Merkholtz', 'eng', null, 'lux:village');
SELECT insert_term('Merl', 'eng', null, 'lux:village');
SELECT insert_term('Mersch', 'eng', null, 'lux:village');
SELECT insert_term('Merscheid', 'eng', null, 'lux:village');
SELECT insert_term('Mertert', 'eng', null, 'lux:village');
SELECT insert_term('Mertzig', 'eng', null, 'lux:village');
SELECT insert_term('Meysembourg', 'eng', null, 'lux:village');
SELECT insert_term('Michelau', 'eng', null, 'lux:village');
SELECT insert_term('Michelbouch', 'eng', null, 'lux:village');
SELECT insert_term('Millbech', 'eng', null, 'lux:village');
SELECT insert_term('Millebaach', 'eng', null, 'lux:village');
SELECT insert_term('Moersdorf', 'eng', null, 'lux:village');
SELECT insert_term('Moesdorf', 'eng', null, 'lux:village');
SELECT insert_term('Moestroff', 'eng', null, 'lux:village');
SELECT insert_term('Mompach', 'eng', null, 'lux:village');
SELECT insert_term('Mondercange', 'eng', null, 'lux:village');
SELECT insert_term('Mondorf-les-Bains', 'eng', null, 'lux:village');
SELECT insert_term('Moutfort', 'eng', null, 'lux:village');
SELECT insert_term('Müllendorf', 'eng', null, 'lux:village');
SELECT insert_term('Müllerthal', 'eng', null, 'lux:village');
SELECT insert_term('Munsbach', 'eng', null, 'lux:village');
SELECT insert_term('Munschecker', 'eng', null, 'lux:village');
SELECT insert_term('Munshausen', 'eng', null, 'lux:village');
SELECT insert_term('Nacherstrooss', 'eng', null, 'lux:village');
SELECT insert_term('Nachtmanderscheid', 'eng', null, 'lux:village');
SELECT insert_term('Nagem', 'eng', null, 'lux:village');
SELECT insert_term('Neidhausen', 'eng', null, 'lux:village');
SELECT insert_term('Neihaisgen', 'eng', null, 'lux:village');
SELECT insert_term('Neudorf', 'eng', null, 'lux:village');
SELECT insert_term('Neunhausen', 'eng', null, 'lux:village');
SELECT insert_term('Niederanven', 'eng', null, 'lux:village');
SELECT insert_term('Niedercorn', 'eng', null, 'lux:village');
SELECT insert_term('Niederdonven', 'eng', null, 'lux:village');
SELECT insert_term('Niederfeulen', 'eng', null, 'lux:village');
SELECT insert_term('Niederpallen', 'eng', null, 'lux:village');
SELECT insert_term('Niederwampach', 'eng', null, 'lux:village');
SELECT insert_term('Niederwiltz', 'eng', null, 'lux:village');
SELECT insert_term('Nocher', 'eng', null, 'lux:village');
SELECT insert_term('Noerdange', 'eng', null, 'lux:village');
SELECT insert_term('Noertrange', 'eng', null, 'lux:village');
SELECT insert_term('Noertzange', 'eng', null, 'lux:village');
SELECT insert_term('Nommern', 'eng', null, 'lux:village');
SELECT insert_term('Nospelt', 'eng', null, 'lux:village');
SELECT insert_term('Nothum', 'eng', null, 'lux:village');
SELECT insert_term('Oberanven', 'eng', null, 'lux:village');
SELECT insert_term('Obercorn', 'eng', null, 'lux:village');
SELECT insert_term('Oberdonven', 'eng', null, 'lux:village');
SELECT insert_term('Obereisenbach', 'eng', null, 'lux:village');
SELECT insert_term('Oberfeulen', 'eng', null, 'lux:village');
SELECT insert_term('Oberpallen', 'eng', null, 'lux:village');
SELECT insert_term('Oberwampach', 'eng', null, 'lux:village');
SELECT insert_term('Oenneschtmillen', 'eng', null, 'lux:village');
SELECT insert_term('Oetrange', 'eng', null, 'lux:village');
SELECT insert_term('Olingen', 'eng', null, 'lux:village');
SELECT insert_term('Olm', 'eng', null, 'lux:village');
SELECT insert_term('Ospern', 'eng', null, 'lux:village');
SELECT insert_term('Osweiler', 'eng', null, 'lux:village');
SELECT insert_term('Pafendall', 'eng', null, 'lux:village');
SELECT insert_term('Parc Hosingen', 'eng', null, 'lux:village');
SELECT insert_term('Peppange', 'eng', null, 'lux:village');
SELECT insert_term('Perlé', 'eng', null, 'lux:village');
SELECT insert_term('Petange', 'eng', null, 'lux:village');
SELECT insert_term('Petit-Nobressart', 'eng', null, 'lux:village');
SELECT insert_term('Pettingen', 'eng', null, 'lux:village');
SELECT insert_term('Pintsch', 'eng', null, 'lux:village');
SELECT insert_term('Pissange', 'eng', null, 'lux:village');
SELECT insert_term('Platen', 'eng', null, 'lux:village');
SELECT insert_term('Pollfermillen', 'eng', null, 'lux:village');
SELECT insert_term('Pommerlach', 'eng', null, 'lux:village');
SELECT insert_term('Pontpierre', 'eng', null, 'lux:village');
SELECT insert_term('Poschend', 'eng', null, 'lux:village');
SELECT insert_term('Potaschberg', 'eng', null, 'lux:village');
SELECT insert_term('Pratz', 'eng', null, 'lux:village');
SELECT insert_term('Préizerdaul', 'eng', null, 'lux:village');
SELECT insert_term('Prettingen', 'eng', null, 'lux:village');
SELECT insert_term('Putscheid', 'eng', null, 'lux:village');
SELECT insert_term('Quatre-Vents', 'eng', null, 'lux:village');
SELECT insert_term('Rambrouch', 'eng', null, 'lux:village');
SELECT insert_term('Rameldange', 'eng', null, 'lux:village');
SELECT insert_term('Reckange', 'eng', null, 'lux:village');
SELECT insert_term('Reckange-sur-Mess', 'eng', null, 'lux:village');
SELECT insert_term('Reckendall', 'eng', null, 'lux:village');
SELECT insert_term('Redange', 'eng', null, 'lux:village');
SELECT insert_term('Reichlange', 'eng', null, 'lux:village');
SELECT insert_term('Reimberg', 'eng', null, 'lux:village');
SELECT insert_term('Reisdorf', 'eng', null, 'lux:village');
SELECT insert_term('Remerschen', 'eng', null, 'lux:village');
SELECT insert_term('Remich', 'eng', null, 'lux:village');
SELECT insert_term('Reuland', 'eng', null, 'lux:village');
SELECT insert_term('Reuler', 'eng', null, 'lux:village');
SELECT insert_term('Rindschleiden', 'eng', null, 'lux:village');
SELECT insert_term('Ringel', 'eng', null, 'lux:village');
SELECT insert_term('Rippig', 'eng', null, 'lux:village');
SELECT insert_term('Rippweiler', 'eng', null, 'lux:village');
SELECT insert_term('Rodange', 'eng', null, 'lux:village');
SELECT insert_term('Rodenbourg', 'eng', null, 'lux:village');
SELECT insert_term('Roder', 'eng', null, 'lux:village');
SELECT insert_term('Rodershausen', 'eng', null, 'lux:village');
SELECT insert_term('Roedgen', 'eng', null, 'lux:village');
SELECT insert_term('Roedt', 'eng', null, 'lux:village');
SELECT insert_term('Roeser', 'eng', null, 'lux:village');
SELECT insert_term('Rolling', 'eng', null, 'lux:village');
SELECT insert_term('Rollingen', 'eng', null, 'lux:village');
SELECT insert_term('Rollingergrund', 'eng', null, 'lux:village');
SELECT insert_term('Rombach', 'eng', null, 'lux:village');
SELECT insert_term('Ronnebësch', 'eng', null, 'lux:village');
SELECT insert_term('Roodt', 'eng', null, 'lux:village');
SELECT insert_term('Roodt-sur-Syre', 'eng', null, 'lux:village');
SELECT insert_term('Rosport', 'eng', null, 'lux:village');
SELECT insert_term('Roudbaach', 'eng', null, 'lux:village');
SELECT insert_term('Roullingen', 'eng', null, 'lux:village');
SELECT insert_term('Rouscht', 'eng', null, 'lux:village');
SELECT insert_term('Rumelange', 'eng', null, 'lux:village');
SELECT insert_term('Rumlange', 'eng', null, 'lux:village');
SELECT insert_term('Saeul', 'eng', null, 'lux:village');
SELECT insert_term('Sandweiler', 'eng', null, 'lux:village');
SELECT insert_term('Sanem', 'eng', null, 'lux:village');
SELECT insert_term('Sassel', 'eng', null, 'lux:village');
SELECT insert_term('Sauerwiss', 'eng', null, 'lux:village');
SELECT insert_term('Savelbur', 'eng', null, 'lux:village');
SELECT insert_term('Schack', 'eng', null, 'lux:village');
SELECT insert_term('Schandel', 'eng', null, 'lux:village');
SELECT insert_term('Scheedheck', 'eng', null, 'lux:village');
SELECT insert_term('Scheidel', 'eng', null, 'lux:village');
SELECT insert_term('Scheidgen', 'eng', null, 'lux:village');
SELECT insert_term('Scheierbierg', 'eng', null, 'lux:village');
SELECT insert_term('Scheierhaff', 'eng', null, 'lux:village');
SELECT insert_term('Schengen', 'eng', null, 'lux:village');
SELECT insert_term('Scherbaach', 'eng', null, 'lux:village');
SELECT insert_term('Schieren', 'eng', null, 'lux:village');
SELECT insert_term('Schifflange', 'eng', null, 'lux:village');
SELECT insert_term('Schiltzbierg', 'eng', null, 'lux:village');
SELECT insert_term('Schimpach', 'eng', null, 'lux:village');
SELECT insert_term('Schleif', 'eng', null, 'lux:village');
SELECT insert_term('Schléiwenhaff', 'eng', null, 'lux:village');
SELECT insert_term('Schlinder', 'eng', null, 'lux:village');
SELECT insert_term('Schlindermanderscheid', 'eng', null, 'lux:village');
SELECT insert_term('Schmëtt', 'eng', null, 'lux:village');
SELECT insert_term('Schmëttewier', 'eng', null, 'lux:village');
SELECT insert_term('Schock', 'eng', null, 'lux:village');
SELECT insert_term('Schoenfels', 'eng', null, 'lux:village');
SELECT insert_term('Schoos', 'eng', null, 'lux:village');
SELECT insert_term('Schouweiler', 'eng', null, 'lux:village');
SELECT insert_term('Schrassig', 'eng', null, 'lux:village');
SELECT insert_term('Schrassig-Kuelebierg', 'eng', null, 'lux:village');
SELECT insert_term('Schrondweiler', 'eng', null, 'lux:village');
SELECT insert_term('Schumannseck', 'eng', null, 'lux:village');
SELECT insert_term('Schuttrange', 'eng', null, 'lux:village');
SELECT insert_term('Schwebach', 'eng', null, 'lux:village');
SELECT insert_term('Schwebsange', 'eng', null, 'lux:village');
SELECT insert_term('Schweich', 'eng', null, 'lux:village');
SELECT insert_term('Schwiedelbrouch', 'eng', null, 'lux:village');
SELECT insert_term('Schwunnendall', 'eng', null, 'lux:village');
SELECT insert_term('Selscheid', 'eng', null, 'lux:village');
SELECT insert_term('Seltz', 'eng', null, 'lux:village');
SELECT insert_term('Senningen', 'eng', null, 'lux:village');
SELECT insert_term('Senningerberg', 'eng', null, 'lux:village');
SELECT insert_term('Septfontaines', 'eng', null, 'lux:village');
SELECT insert_term('Siebenaler', 'eng', null, 'lux:village');
SELECT insert_term('Simmerschmelz', 'eng', null, 'lux:village');
SELECT insert_term('Siwemuergen', 'eng', null, 'lux:village');
SELECT insert_term('Soleuvre', 'eng', null, 'lux:village');
SELECT insert_term('Sonlez', 'eng', null, 'lux:village');
SELECT insert_term('Sprinkange', 'eng', null, 'lux:village');
SELECT insert_term('Stadtbredimus', 'eng', null, 'lux:village');
SELECT insert_term('Steekräiz', 'eng', null, 'lux:village');
SELECT insert_term('Stegen', 'eng', null, 'lux:village');
SELECT insert_term('Steinfort', 'eng', null, 'lux:village');
SELECT insert_term('Steinheim', 'eng', null, 'lux:village');
SELECT insert_term('Steinsel', 'eng', null, 'lux:village');
SELECT insert_term('Stockem', 'eng', null, 'lux:village');
SELECT insert_term('Stolzembourg', 'eng', null, 'lux:village');
SELECT insert_term('Strassen', 'eng', null, 'lux:village');
SELECT insert_term('Surré', 'eng', null, 'lux:village');
SELECT insert_term('Syrdall', 'eng', null, 'lux:village');
SELECT insert_term('Syren', 'eng', null, 'lux:village');
SELECT insert_term('Tadler', 'eng', null, 'lux:village');
SELECT insert_term('Tandel', 'eng', null, 'lux:village');
SELECT insert_term('Tarchamps', 'eng', null, 'lux:village');
SELECT insert_term('Tétange', 'eng', null, 'lux:village');
SELECT insert_term('Todlermillen', 'eng', null, 'lux:village');
SELECT insert_term('Tomm', 'eng', null, 'lux:village');
SELECT insert_term('Tossebierg', 'eng', null, 'lux:village');
SELECT insert_term('Trintange', 'eng', null, 'lux:village');
SELECT insert_term('Troine', 'eng', null, 'lux:village');
SELECT insert_term('Troine-Route', 'eng', null, 'lux:village');
SELECT insert_term('Troisvierges', 'eng', null, 'lux:village');
SELECT insert_term('Tuntange', 'eng', null, 'lux:village');
SELECT insert_term('Uebersyren', 'eng', null, 'lux:village');
SELECT insert_term('Untereisenbach', 'eng', null, 'lux:village');
SELECT insert_term('Urspelt', 'eng', null, 'lux:village');
SELECT insert_term('Useldange', 'eng', null, 'lux:village');
SELECT insert_term('Vallée de l''Ernz', 'eng', null, 'lux:village');
SELECT insert_term('Verluerekascht', 'eng', null, 'lux:village');
SELECT insert_term('Vesquenhaff', 'eng', null, 'lux:village');
SELECT insert_term('Vianden', 'eng', null, 'lux:village');
SELECT insert_term('Vichten', 'eng', null, 'lux:village');
SELECT insert_term('Wahl', 'eng', null, 'lux:village');
SELECT insert_term('Wahlhausen', 'eng', null, 'lux:village');
SELECT insert_term('Waldbillig', 'eng', null, 'lux:village');
SELECT insert_term('Waldbredimus', 'eng', null, 'lux:village');
SELECT insert_term('Walferdange', 'eng', null, 'lux:village');
SELECT insert_term('Wallendorf-Pont', 'eng', null, 'lux:village');
SELECT insert_term('Walsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Wandhaff', 'eng', null, 'lux:village');
SELECT insert_term('Warken', 'eng', null, 'lux:village');
SELECT insert_term('Wasserbillig', 'eng', null, 'lux:village');
SELECT insert_term('Watrange', 'eng', null, 'lux:village');
SELECT insert_term('Wecker', 'eng', null, 'lux:village');
SELECT insert_term('Weicherdange', 'eng', null, 'lux:village');
SELECT insert_term('Weidingen', 'eng', null, 'lux:village');
SELECT insert_term('Weiler', 'eng', null, 'lux:village');
SELECT insert_term('Weilerbaach', 'eng', null, 'lux:village');
SELECT insert_term('Weiler-la-Tour', 'eng', null, 'lux:village');
SELECT insert_term('Weimershaff', 'eng', null, 'lux:village');
SELECT insert_term('Weimerskirch', 'eng', null, 'lux:village');
SELECT insert_term('Weiswampach', 'eng', null, 'lux:village');
SELECT insert_term('Welfrange', 'eng', null, 'lux:village');
SELECT insert_term('Wellenstein', 'eng', null, 'lux:village');
SELECT insert_term('Welscheid', 'eng', null, 'lux:village');
SELECT insert_term('Welsdorf', 'eng', null, 'lux:village');
SELECT insert_term('Wemperhaard', 'eng', null, 'lux:village');
SELECT insert_term('Weydig', 'eng', null, 'lux:village');
SELECT insert_term('Weyer', 'eng', null, 'lux:village');
SELECT insert_term('Wickrange', 'eng', null, 'lux:village');
SELECT insert_term('Wilspull', 'eng', null, 'lux:village');
SELECT insert_term('Wiltz', 'eng', null, 'lux:village');
SELECT insert_term('Wilwerdange', 'eng', null, 'lux:village');
SELECT insert_term('Wilwerwiltz', 'eng', null, 'lux:village');
SELECT insert_term('Wincrange', 'eng', null, 'lux:village');
SELECT insert_term('Winseler', 'eng', null, 'lux:village');
SELECT insert_term('Wintrange', 'eng', null, 'lux:village');
SELECT insert_term('Wobierg', 'eng', null, 'lux:village');
SELECT insert_term('Wolpert', 'eng', null, 'lux:village');
SELECT insert_term('Wolwelange', 'eng', null, 'lux:village');
SELECT insert_term('Wormeldange', 'eng', null, 'lux:village');
SELECT insert_term('Zittig', 'eng', null, 'lux:village');
UPDATE termlists_terms SET sort_order = 10*id WHERE termlist_id = (SELECT id FROM termlists WHERE external_key='lux:village');
INSERT INTO location_attributes (caption, data_type, created_on, created_by_id, updated_on, updated_by_id, termlist_id, multi_value, public) VALUES (
	'VillageDD', 'L', now(), 1, now(), 1, (select id from termlists where external_key='lux:village'), 'f', 't');
